### ISSUE TITLE
`BeatmapStore` grows indefinitely (probably needs some kind of expiry logic)

### ISSUE THREAD

**Issue by peppy** [ppy/osu-queue-score-statistics#143]
When running in lower memory scenarios this could become an issue.

It's actually caused production failures after running for several weeks. The failures may only occur on scores which haven't had a beatmap cached, meaning the queue processor doesn't see enough consecutive errors to quit out, and causing intermittent score processing failures for some users.

**Comment by smoogipoo** [comment]
In cases like this (and `osu-beatmap-difficulty-lookup-cache`), I tend to gravitate to wanting to use one of the .NET caching extensions (https://learn.microsoft.com/en-us/dotnet/core/extensions/caching) that both have some concept of "size".

It might be an interesting venture to see if that could be used for more of these k8s components...
