### ISSUE TITLE
osu!stable score screen needs consideration for the new PP processing

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-queue-score-statistics#183]
I don't know how to title this issue to be most effective, sorry.

1. `osu-web-10` polls `osu_scores_high` table waiting for the `pp` column to be processed. This column will no longer receive data after osu-performance is taken offline.
2. `osu-web-10` expects `osu_user_stats` to be updated in the same transaction as the `pp` column from the above, as it immediately returns the total PP/rank from there as soon as the `pp` column is populated. `osu-queue-score-statistics` does not run everything in a single transaction.

Technically, we can populate the `pp` column from [`UserTotalPerformanceProcessor`](https://github.com/ppy/osu-queue-score-statistics/blob/master/osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs).  
Note: Currently [`ScorePerformanceProcessor`](https://github.com/ppy/osu-queue-score-statistics/blob/master/osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs) doesn't update the in-memory `SoloScoreInfo` pp value, and only inserts it into the database. We should probably make it update the model if this is the path forward.

**Comment by peppy** [comment]
It seems like this should be okay because we are already grouping all processor updates in a single database transaction (phew):

https://github.com/ppy/osu-queue-score-statistics/blob/2e76451d61efe660aa8c6cf6db8b2c195f03ff65/osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs#L125

**Comment by peppy** [comment]
Leaving issue open as we still need to populate `pp` values back to the old table. This is probably something we want to do in the processor at this end.

**Comment by bdach** [comment]
> This is probably something we want to do in the processor at this end (ie. `UPDATE osu_scores_high SET pp = @pp WHERE score_id = @legacyScoreId`, probably after #181 is merged for sanity

I don't think this is being done yet (as was pointed out [a few days ago on discord](https://discord.com/channels/188630481301012481/188630652340404224/1194750267082682479))? Should this issue have been closed by the PR above?

**Comment by peppy** [comment]
Probably fine to leave open for now yeah.
