### ISSUE TITLE
Update ranks on "lazer mode" leaderboards to match latest specifications

### ISSUE THREAD

**Issue by peppy** [ppy/osu-queue-score-statistics#222]

**Comment by peppy** [comment]
This is currently being fixed on all existing scores using https://github.com/ppy/osu-queue-score-statistics/pull/203 + https://github.com/ppy/osu-wiki/pull/10907.

**Comment by bdach** [comment]
> using https://github.com/ppy/osu-queue-score-statistics/pull/203 + https://github.com/ppy/osu-wiki/pull/10907.

Second link looks pretty wrong.

**Comment by smoogipoo** [comment]
Does this issue need to stay open?

**Comment by peppy** [comment]
I'm still running ongoing fixes for this. osu! ruleset is complete, others are WIP. I've got a huge backlog of verification and maintenance operations and this is being slotted in where i find the free time (running one at a time max to avoid any further repercussions).

Currently osu!taiko is running (since yesterday), other rulesets will follow.

I'll close this when done 😄

**Comment by peppy** [comment]
This has now been completed across all rulesets.
