### ISSUE TITLE
User total processing commands don't update mania key-mode tables

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-queue-score-statistics#295]
Processing user totals runs the `UserTotalPerformanceProcessor`:

https://github.com/ppy/osu-queue-score-statistics/blob/3ac03768bb93cb2568d1b87f02c5c35953b48c74/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs#L75

But not the [`ManiaKeyModeUserStatsProcessor.cs`](https://github.com/ppy/osu-queue-score-statistics/blob/3ac03768bb93cb2568d1b87f02c5c35953b48c74/osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStatsProcessor.cs).

**Comment by peppy** [comment]
Forgot about this one, will look into it this week.
