### ISSUE TITLE
Limit builds fetched to only builds with `allow_performance = true OR allow_ranking = true`

### ISSUE THREAD

**Issue by peppy** [ppy/osu-queue-score-statistics#54]
Should be the only ones we care about.

**Comment by smoogipoo** [comment]
Why `allow_ranking`? For other non-performance use-cases?

**Comment by peppy** [comment]
Yeah, we'll probably want to factor that in for the other processors at some point.

**Comment by peppy** [comment]
Actually maybe not, because that flag is dynamic based on the current point in time, which isn't too relevant to scores set in the past.
