### ISSUE TITLE
Playcount incrementing should check for valid plays

### ISSUE THREAD

**Issue by peppy** [ppy/osu-queue-score-statistics#63]
Minimum time played and score (and making sure auto retry mods like perfect cannot result in playcount farming).

**Comment by frenzibyte** [comment]
Can give this an attempt, will need stable code.

**Comment by peppy** [comment]
I think there's actually logic within stable itself to define the cutoff, but I couldn't find it immediately. Maybe you'll have more luck than I did.

It's probably fine to start with some logical restrictions and build on them from there. Disabling any mod combinations that can result in completely automated play (ie. "Perfect" + something which hits objects), adding an arbitrary minimum object-hit count (maybe 20 or so? with considerations for beatmaps which may have less than that).

**Comment by smoogipoo** [comment]
```
(AudioEngine.Time - SkipBoundary > 8000 || currentScore.Pass) &&
(currentScore.TotalScore > 10000 || currentScore.Pass) && ...
```

**Comment by peppy** [comment]
I think we still want this in this year. @bdach maybe a quick one you can tackle?
