### ISSUE TITLE
Elasticsearch schema version lookup needs to use new lookup list (and poll for changes)

### ISSUE THREAD

**Issue by peppy** [ppy/osu-queue-score-statistics#78]
As per inline comment:

https://github.com/ppy/osu-queue-score-statistics/blob/a33dfa0c89e4b5a348b9a7b839773203c1fa9242/osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs#L163-L164

See: https://github.com/ppy/osu-elastic-indexer/blob/c9d455a77217417ee795218a4441e5a8f2d6942a/osu.ElasticIndexer/Redis.cs#L25-L28

**Comment by bdach** [comment]
Fixed by #178?
